- name: deploy_neo_agent_on_onyx
  hosts: l-csi-2700s-tmp-01
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: onyx
    image_name: "mellanox/telemetry-agent"
    version: "latest"
    destination_folder: "/var/opt/tms/images/"
    local_copy: "FALSE"
    tgz_file: ""
    wjhgraf_port: 8093
    wjhgraf_ip: ""
    memory_util: 300
    cpu_util: 0.5

    help: |
         Parameters available with their default values:

  tasks:
   - name: help_menu
     debug:
       msg:  "{{ help.split('\n') }}"
     tags: help
     delegate_to: localhost
     run_once: true

   - name: check wjhgraf_ip
     debug:
        msg: "{{ wjhgraf_ip | ipaddr }}"
     register: isIp

   - fail:
      msg: "The variable wjhgraf_ip: {{wjhgraf_ip}} is not a vaild ip address."
     when: not isIp.msg

   - name: copy_docker_image_to_switch
     net_put:
       src: "{{ tgz_file }}"
       dest: "{{ destination_folder }}"
       mode: binary
       protocol: scp
     when: local_copy == "TRUE"

   - name: disable_wjh
     onyx_config:
       commands: no what-just-happened all enable

   - name: enable_docker_on_switch
     onyx_config:
      commands: no docker shutdown

   - name: check_docker_is_enabled
     onyx_command:
      commands: show docker
      wait_for:
        - result[0] contains enabled

   - name: stop_running_containers
     onyx_config:
      commands: "no docker start telemetry-agent"

   - name: load_docker_image
     onyx_config:
       commands: docker load {{tgz_file}}
     when: local_copy == "TRUE"

   - name: check_docker_image_is_loaded
     onyx_command:
       commands: show docker images | include "{{image_name}}"
       wait_for:
         - result[0] contains {{}}
     when: local_copy == "TRUE"

   - name: start_docker_container
     onyx_config:
          commands: docker start {{image_name}} {{version}} telemetry-agent now-and-init cpus {{cpu_util}} memory {{memory_util}} privileged sdk network

   - name: check_container_is_started
     onyx_command:
         commands: show docker ps | include telemetry-agent
         wait_for:
          - result[0] contains " Up "

   - name: copy_sdk
     onyx_config:
          commands: docker copy-sdk telemetry-agent to /
   - debug:
       msg: "start wjh session with:  docker exec telemetry-agent '/opt/telemetry/utils/run_wjh_session.sh {{wjhgraf_ip}} {{wjhgraf_port}}'"

   - name: run wjh_session
     onyx_config:
          commands: docker exec telemetry-agent "/opt/telemetry/utils/run_wjh_session.sh {{wjhgraf_ip}} {{wjhgraf_port}}"

   - name: save_config
     onyx_config:
       commands: configuration write
