---
- name: DUG_plabook
  hosts: dug
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: onyx

  tasks:
   - import_role:
       name: dug_leaf
     tags: dug_leaf

   - import_role:
        name: dug_spine
     tags: dug_spine

     tags: dug_spine
   - import_role:
        name: dug_super_spine
     tags: dug_super_spine
