---
- name: mlag_playbook
  hosts: MLAG
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: onyx
    reset: factory
    clean_config: "true"
    wait_for_protocol_port: 22
    force_upgrade_downgrade: "true"
    path: "/tmp/"
    cpu: "X86_64"   # X86_64 | PPC_M460EX
    user: root
    password: 3tango
    remote_ip: l-csi-demo-05
    internal_network: "no"
    ntp_server: "216.239.35.0"
    version: 3.6.8134
    log_path: ./ansible.log
    debug: True
  tasks:
    - import_role:
        name: onyx_clean_config
      tags: clean_config
      when: clean_config == "true"
 
    - import_role:
        name: onyx_wait
      when: clean_config == "true"
      tags: wait1
    - onyx_config:
       commands: ssh client user admin known-host "{{remote_ip}}" remove
    
    - import_role:
        name: onyx_image_fetch_install
      tags: image_install	

    - import_role:
        name: onyx_boot_next_save_config_reload
      tags: boot_next
    
    - import_role:
        name: onyx_wait
      tags: wait2
  
    - import_role:
        name: onyx_basic_lab_mgmt_config
      tags: basic_config
    
    - import_role:
        name: mlag
      tags: mlag

  roles:
  # - { role: onyx_clean_config, tags: ['clean_config']}
  # - { role: onyx_basic_lab_mgmt_config, tags: ['mgmt_config']}
  # - { role: mlag, tags: ['role_mlag'] }
