- name: onyx_ssd_fw_upgrade
  hosts: l-csi-demo-2100-44,l-csi-demo-2100-45,l-csi-demo-2100-46,l-csi-demo-2100-47
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    ansible_network_os: onyx
    docker_file: onyx_ssd_fw_upgrade-latest_Docker.tgz
    transfer_protocol: scp
    dst_folder: /var/opt/tms/images/

  tasks:
     - name: copy_file_to_device
       net_put:
         dest: "{{ dst_folder }}"
         mode: binary
         protocol: "{{ transfer_protocol }}"
         src: "{{ docker_file }}"

#     - name: upgrade
#       onyx_config:
#            commands:
#               - no docker shutdown
#               - docker load onyx_ssd_fw_upgrade-latest_Docker.tgz
#               - docker start onyx_ssd_fw_upgrade latest ssd now privileged network
#               - docker exec ssd  /tmp/ssd_fw_upgrade.sh
     - name: upgrade_via_ssh
       delegate_to: localhost
       shell: sshpass -p {{ansible_ssh_pass}} ssh {{ansible_ssh_user}}@{{inventory_hostname}} cli \"enable\" \"conf t\" \"no docker shutdown\" \"docker load  onyx_ssd_fw_upgrade-latest_Docker.tgz\" \"docker start onyx_ssd_fw_upgrade latest ssd now privileged network\" \"docker exec ssd  \/tmp\/ssd_fw_upgrade.sh\"
