---
- name: cl-basic
  hosts: cumulus
  gather_facts: no
  become: yes
  become_method: sudo

  tasks:
    - name: apt_repo
      apt_repository:
        repo: deb http://http.us.debian.org/debian jessie main
    - name: apt_repo
      apt_repository:
        repo: deb http://security.debian.org/ jessie/updates main
    - name: locate
      apt:
        name: locate
        state: present
    - name: vim
      apt:
        name: locate
        state: present
