---
- name: innodisk_ssd_fw_upgrade
  hosts: switch_names| groups
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
    single: "false"
  tasks:
   - name: copy_ssd_fw_file_to_switch
     copy:
        src=./S16425M.bin
        dest=/tmp/S16425M.bin

   - name: copy_hdparms_deb
     copy:
         src=./hdparm_9.51+ds-1+deb9u1_amd64.deb
         dest=/tmp/hdparm_9.51+ds-1+deb9u1_amd64.deb

#   - name: copy_cumulus-trim
#     copy:
#         src=/etc/ansible/cumulus-trim_1.0.0-PartnerTesting-cl3u1_all.deb
#         dest=/tmp/cumulus-trim_1.0.0-PartnerTesting-cl3u1_all.deb

   - name: install_hdparms
     shell: dpkg -i ./hdparm_9.51+ds-1+deb9u1_amd64.deb
     args:
      chdir: /tmp/
     become: true
     become_method: sudo
     tags: install_hdparms

   - name: apt_get_update
     shell: apt-get -y update

   - name: install cumulus-trim
     shell: apt-get -y install cumulus-trim

   - name: start_trim
     shell: /sbin/fstrim -v /

   - name: check_current_fw_version
     shell: sudo hdparm -i /dev/sda | grep FwRev | cut -d "," -f 2 | cut -d "=" -f 2
     register: current_fw_version
     tags: check_current_fw

   - name: print_current_fw_version
     debug:
       msg: "SSD FW version: {{current_fw_version.stdout}}"
     tags: print_fw

   - name: upgrade_ssd_fw
     shell: sudo hdparm --yes-i-know-what-i-am-doing --please-destroy-my-drive --fwdownload S16425M.bin /dev/sda
     args:
      chdir: /tmp/
     when: current_fw_version.stdout == "S15A19"
     register: upgrade_result
     tags: upgrade_ssd

   - name: print_done1
     debug:
        msg: "Upgrade result before power cycle:  {{upgrade_result.stdout_lines}} {{upgrade_result.stderr_lines}}"
     when: upgrade_result.stdout is defined
     tags: print_done1

   - name: print_done2
     debug:
       msg: "SSD FW is already at needed level = {{current_fw_version.stdout}}, no need to POWER CYCLE"
     when: upgrade_result.stdout is not defined
     tags: print_done2
