---
#- name: clean_files
#  shell: sshpass -p {{switch_password}} sftp -b {{role_path}}/files/onyx_dirs.txt {{ansible_ssh_user}}@{{inventory_hostname}}
#  delegate_to: localhost

- name: get_image_names
  onyx_command:
     commands: show images
  register: images

- name: get_sysdump_names
  onyx_command:
     commands: show files debug-dump
  register: sysdump

- name: get_pcap_names
  onyx_command:
     commands: show files tcpdump
  register: tcpdump

- name: get_pcap_names
  onyx_command:
     commands: show files snapshot
  register: snapshot

#- debug:
#    msg: "Image file: {{item.split(':')[1]}} "
#  with_items: "{{ images.stdout_lines }}"
#  when: "'.img' in item or '.tbz' in item"

- name: delete_img_files
  onyx_command:
    commands: "image delete {{ item.split(':')[1] }} "
  with_items: "{{ images.stdout_lines }}"
  when:
   - "'.img' in item or '.tbz' in item"


- name: delete_sysdump_files
  onyx_command:
    commands: file debug-dump delete all

- name: delete_pcap_files
  onyx_command:
    commands: "file tcpdump delete {{ item }} "
  with_items: "{{ tcpdump.stdout_lines }}"
  when:
   - "'pcap' in item"
