---
- name: get_image_names
  onyx_command:
     commands: show images
  register: images
  tags: images

- name: get_sysdump_names
  onyx_command:
     commands: show files debug-dump
  register: sysdump

- name: get_pcap_names
  onyx_command:
     commands: show files tcpdump
  register: tcpdump

- name: get_pcap_names
  onyx_command:
     commands: show files snapshot
  register: snapshot

- name: delete_img_files
  onyx_command:
    commands: "image delete {{ item.split(':')[1] }} "
  with_items: "{{ images.stdout_lines }}"
  when:
   - "'.img' in item or '.tbz' in item"


- name: delete_sysdump_files
  onyx_command:
    commands: file debug-dump delete all

- name: delete_pcap_files
  onyx_command:
    commands: "file tcpdump delete {{ item }} "
  with_items: "{{ tcpdump.stdout_lines }}"
  when:
   - "'pcap' in item"
