---
#- name: clean_files
#  shell: sshpass -p {{switch_password}} sftp -b {{role_path}}/files/onyx_dirs.txt {{ansible_ssh_user}}@{{inventory_hostname}}
#  delegate_to: localhost


- name: get_image_names
  onyx_command:
     command: show images | json-print
  register: images

- debug:
    msg: images.stdout
