---

- name: delete_clean_config_file
  onyx_command:
     commands:
      - show configuration files | include " clean "
  register: clean_exists

- name: delete_clean_config_file
  onyx_config:
     lines:
      - configuration delete clean
  when: '"clean" in clean_exists.stdout'

- name: clean_config
  onyx_config:
     lines:
      - configuration new clean factory keep-connect
      - configuration switch-to clean no-reboot
      - configuration delete initial
      - configuration copy clean initial
      - configuration switch-to initial no-reboot
      - configuration delete clean
      - configuration write
      - reload force
  register: output
  ignore_errors: yes
