---
#- name: gather facts
#  onyx_facts:
#    gather_subset: all
- name: copy_file_to_device
  net_put:
      dest: "{{ destination_folder }}"
      mode: binary
      protocol: "{{ transfer_protocol }}"
      src: "{{ source_file }}"
