---
- hosts: leaf2
  connection: network_cli
  become: yes
  become_method: enable
  gather_facts: no
  tasks:

  - onyx_config:
      commands:
        - no cli default prompt confirm-unsaved
        - reload
    ignore_errors: yes
  - pause:
      minutes: 3
  - onyx_command:
      commands: show clock
  - onyx_config:
      commands: interfece ethernet 1/1 description ansible_test
