---

- name: run_a_command
  onyx_command:
         commands: "{{ command }}"
  register: output
- name: print output
  debug:
    msg:
      - "The output of the command: {{command}}"
      - "{{ output.stdout }}"
