---
- name: check_if_x86_64
  onyx_command:
    commands: show version concise
  register: concise_version

- name: get_facts
  onyx_facts:
     gather_subset: "{{ subset }}"
  when:  '"X86_64" in concise_version.stdout'
  register: facts_received
