---
- name: send_mail
  mail:
     body: "{{mail_body}}"
     host: "{{mail_server}}"
     subject: "{{mail_subject}}"
     from: "{{mail_from}}"
     to: "{{mail_to_list}}"
     attach: "{{attach}}"
     timeout: 60
     secure: "{{secure}}"
  delegate_to: localhost
