---
#- name: get_facts_from_device
#  onyx_facts:
#    gather_subset: version
- name: image boot next and reload with upgrade_downgrade_force
  onyx_config:
      lines:
        - image boot next
        - configuration write
        - no boot next fallback-reboot enable
        - reload
      backup: yes
  when:
#   - ansible_net_version['Product release']  != version
   - force_upgrade_downgrade == "true"
  ignore_errors: yes

- name: image boot next and reload without upgrade_downgrade_force
  onyx_config:
      lines:
        - image boot next
        - configuration write
        - reload
      backup: yes
  when:
#    - ansible_net_version['Product release']  != version
    - force_upgrade_downgrade == "false"
  ignore_errors: yes
